### PR TITLE
Adapted Microsoft Reference Sources for Unity

### PR DESCRIPTION
**Pull request by movrajr**
Removed attributes and dummy classes.

### CODE REVIEW

**Comment by jesusdesantos** [comment]
I am not an expert in github but it seems that this pull request has been done against themicahosborne/UnityMVVM which is still not updated with our repository (we are waiting this pull request to be integrated https://github.com/micahosborne/UnityMVVM/pull/1).

So I think you should branch from our repository and send us the pull request again. Could you do it?

**Comment by movrajr** [comment]
The beauty of GitHub is that it does not matter which repository we fork. Different forks can be synced to each other. Even though movrajr/UnityMVVM and Noesis/UnityMVVM both forked micahosborne/UnityMVVM, they do not have to fork from one each other in other to sync the differences. It is taken care of by GitHub.

I have sent pull requests to both Noesis/UnityMVVM and themicahosborne/UnityMVVM because I believe movrajr/UnityMVVM is the definite version. It is closest to the original source, Microsoft's source code, instead of being based on what is likely reverse-engineered code taken from the Mono project. 

For example, movrajr/UnityMVVM has the most complete version of the class NotifyCollectionChangedEventArgs. themicahosborne/UnityMVVM and Noesis/UnityMVVM miss several constructors. The lack of a particular constructor makes a certain call from a collection change event fall back to the wrong constructor, which causes an invalid operation exception.

Similar to Noesis' version I have surrounded the classes with NETFX_CORE preprocessor directives so you can build  Windows Phone/Windows Store apps with the Microsoft compiler.

The merge conflict is possibly caused by a filename mismatch. Noesis/UnityMVVM consists of 3 .cs files whereas movrajr/UnityMVVM has 4. I have split INotifyCollectionChanged.cs into notifycollectionchangedeventargs.cs and INotifyCollectionChanged.cs to reflect Microsoft's source code.

Note that themicahosborne/UnityMVVM is not included with the uFrame asset from the Unity Asset Store. Instead it is this one: [uFrame/UnityMVVM](https://github.com/InvertGames/uFrame/tree/master/UnityMVVM). Unfortunately it is not WPF compliant. Compare: 
- [Microsoft's NotifyCollectionChangedEventHandler](http://msdn.microsoft.com/en-us/library/system.collections.specialized.notifycollectionchangedeventhandler%28v=vs.110%29.aspx)
- [uFrame's NotifyCollectionChangedEventHandler](https://github.com/InvertGames/uFrame/blob/master/UnityMVVM/NotifyCollectionChangedEventHandler.cs) 

The integration of Noesis with uFrame is succesful when using movrajr/UnityMVVM together with the Noesis 1.2 beta and my [MVVM-MS-Reference-Source branch of uFrame 1.5](https://github.com/movrajr/uFrame/tree/MVVM-MS-Reference-Source). All that is left are some adaptions of uFrame's code generator whose source code is closed. I have reported the required adaptions on [uFrame's Trello board](https://trello.com/b/dXaihYXE/uframe-roadmap) in the WPF Bugs list.

**Comment by jesusdesantos** [comment]
My confusion is due to the fact that I cannot see the diff of your changes against Noesis/UnityMVVM, it seems it is taken as base the files stored in themicahosborne/UnityMVVM. Or probably that is correct and problem is that due to the conflict I cannot see it.

**Comment by movrajr** [comment]
Well, that is indeed weird. Try the new pull request.

**Pull request closed without merging**
